# Generated by Django 3.1.4 on 2020-12-15 00:22

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
