# Generated by Django 3.1.4 on 2020-12-31 19:16

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201231_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=martor.models.MartorField(),
        ),
    ]
